
services:
  ai_service:
    build: ./services/ai_service
    ports:
      - "8000:8000"
    volumes:
      - ./services/ai_service:/app
    env_file:
      - .env

  weather_service:
    build: ./services/weather_service
    ports:
      - "8001:8001"
    volumes:
      - ./services/weather_service:/app
    env_file:
      - .env
